USE ea_coach_dna_calibration;

-- =========================================================
-- PURPOSE
-- Load raw nflverse play-by-play CSVs into raw_pbp for:
-- - 2023 baseline season
-- - 2024 baseline season
-- - 2025 team-profile + baseline season
--
-- This script clears the staging table first so reloads are clean.
-- =========================================================

TRUNCATE TABLE raw_pbp;

-- =========================================================
-- NOTES
-- Before running:
-- 1. Make sure LOCAL INFILE is enabled
-- 2. Start MySQL with --local-infile=1
-- 3. Confirm these files exist:
--    /Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2023.csv
--    /Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2024.csv
--    /Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2025.csv
-- =========================================================

-- =========================================================
-- LOAD 2023
-- =========================================================

LOAD DATA LOCAL INFILE '/Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2023.csv'
INTO TABLE raw_pbp
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    play_id,
    game_id,
    old_game_id,
    home_team,
    away_team,
    season_type,
    week,
    posteam,
    @ignore,
    defteam,
    side_of_field,
    yardline_100,
    game_date,
    quarter_seconds_remaining,
    half_seconds_remaining,
    game_seconds_remaining,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    qtr,
    down,
    goal_to_go,
    game_clock,
    yrdln,
    ydstogo,
    @ignore,
    play_description,
    play_type,
    yards_gained,
    shotgun,
    no_huddle,
    qb_dropback,
    qb_kneel,
    qb_spike,
    @ignore,
    @ignore,
    pass_location,
    air_yards,
    yards_after_catch,
    run_location,
    run_gap,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    posteam_score,
    defteam_score,
    score_differential,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    epa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    wp,
    def_wp,
    home_wp,
    away_wp,
    wpa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @fd_rush,
    @fd_pass,
    @fd_penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    incomplete_pass,
    @ignore,
    interception,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    safety,
    penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    rush_attempt,
    pass_attempt,
    sack,
    touchdown,
    pass_touchdown,
    rush_touchdown,
    return_touchdown,
    extra_point_attempt,
    two_point_attempt,
    field_goal_attempt,
    kickoff_attempt,
    punt_attempt,
    fumble,
    complete_pass
)
SET
    season = 2023,
    source_season = 2023,
    source_file = 'pbp_2023.csv',
    first_down = CASE
        WHEN COALESCE(@fd_rush, 0) + COALESCE(@fd_pass, 0) + COALESCE(@fd_penalty, 0) > 0 THEN 1
        ELSE 0
    END;

-- =========================================================
-- LOAD 2024
-- =========================================================

LOAD DATA LOCAL INFILE '/Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2024.csv'
INTO TABLE raw_pbp
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    play_id,
    game_id,
    old_game_id,
    home_team,
    away_team,
    season_type,
    week,
    posteam,
    @ignore,
    defteam,
    side_of_field,
    yardline_100,
    game_date,
    quarter_seconds_remaining,
    half_seconds_remaining,
    game_seconds_remaining,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    qtr,
    down,
    goal_to_go,
    game_clock,
    yrdln,
    ydstogo,
    @ignore,
    play_description,
    play_type,
    yards_gained,
    shotgun,
    no_huddle,
    qb_dropback,
    qb_kneel,
    qb_spike,
    @ignore,
    @ignore,
    pass_location,
    air_yards,
    yards_after_catch,
    run_location,
    run_gap,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    posteam_score,
    defteam_score,
    score_differential,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    epa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    wp,
    def_wp,
    home_wp,
    away_wp,
    wpa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @fd_rush,
    @fd_pass,
    @fd_penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    incomplete_pass,
    @ignore,
    interception,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    safety,
    penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    rush_attempt,
    pass_attempt,
    sack,
    touchdown,
    pass_touchdown,
    rush_touchdown,
    return_touchdown,
    extra_point_attempt,
    two_point_attempt,
    field_goal_attempt,
    kickoff_attempt,
    punt_attempt,
    fumble,
    complete_pass
)
SET
    season = 2024,
    source_season = 2024,
    source_file = 'pbp_2024.csv',
    first_down = CASE
        WHEN COALESCE(@fd_rush, 0) + COALESCE(@fd_pass, 0) + COALESCE(@fd_penalty, 0) > 0 THEN 1
        ELSE 0
    END;

-- =========================================================
-- LOAD 2025
-- =========================================================

LOAD DATA LOCAL INFILE '/Users/Tip/Desktop/ea-coach-dna-calibration/data/raw/pbp_2025.csv'
INTO TABLE raw_pbp
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    play_id,
    game_id,
    old_game_id,
    home_team,
    away_team,
    season_type,
    week,
    posteam,
    @ignore,
    defteam,
    side_of_field,
    yardline_100,
    game_date,
    quarter_seconds_remaining,
    half_seconds_remaining,
    game_seconds_remaining,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    qtr,
    down,
    goal_to_go,
    game_clock,
    yrdln,
    ydstogo,
    @ignore,
    play_description,
    play_type,
    yards_gained,
    shotgun,
    no_huddle,
    qb_dropback,
    qb_kneel,
    qb_spike,
    @ignore,
    @ignore,
    pass_location,
    air_yards,
    yards_after_catch,
    run_location,
    run_gap,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    posteam_score,
    defteam_score,
    score_differential,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    epa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    wp,
    def_wp,
    home_wp,
    away_wp,
    wpa,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @fd_rush,
    @fd_pass,
    @fd_penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    incomplete_pass,
    @ignore,
    interception,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    safety,
    penalty,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    @ignore,
    rush_attempt,
    pass_attempt,
    sack,
    touchdown,
    pass_touchdown,
    rush_touchdown,
    return_touchdown,
    extra_point_attempt,
    two_point_attempt,
    field_goal_attempt,
    kickoff_attempt,
    punt_attempt,
    fumble,
    complete_pass
)
SET
    season = 2025,
    source_season = 2025,
    source_file = 'pbp_2025.csv',
    first_down = CASE
        WHEN COALESCE(@fd_rush, 0) + COALESCE(@fd_pass, 0) + COALESCE(@fd_penalty, 0) > 0 THEN 1
        ELSE 0
    END;